name: Sync Mirror

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        env:
          COS_SECRET: ${{ secrets.COS_SECRET }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_MAP_BUCKET: ${{ secrets.COS_MAP_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
        with:
          node-version: 20
      - run: npm ci
      - run: npm run start
