name: Sync Mirror

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - run: bun install
      - run: bun run start
        env:
          COS_SECRET: ${{ secrets.COS_SECRET }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_MAP_BUCKET: ${{ secrets.COS_MAP_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
          UPLOAD: true
